/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MontagemDeSetupsRouteImport } from './routes/montagem-de-setups'
import { Route as PersonalizacaoRouteImport } from './routes/personalizacao'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ReformaEUpgradeRouteImport } from './routes/reforma-e-upgrade'
import { Route as SuporteTecnicoRouteImport } from './routes/suporte-tecnico'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MontagemDeSetupsRoute = MontagemDeSetupsRouteImport.update({
  id: '/montagem-de-setups',
  path: '/montagem-de-setups',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizacaoRoute = PersonalizacaoRouteImport.update({
  id: '/personalizacao',
  path: '/personalizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformaEUpgradeRoute = ReformaEUpgradeRouteImport.update({
  id: '/reforma-e-upgrade',
  path: '/reforma-e-upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteTecnicoRoute = SuporteTecnicoRouteImport.update({
  id: '/suporte-tecnico',
  path: '/suporte-tecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/montagem-de-setups': typeof MontagemDeSetupsRoute
  '/personalizacao': typeof PersonalizacaoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/reforma-e-upgrade': typeof ReformaEUpgradeRoute
  '/suporte-tecnico': typeof SuporteTecnicoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/montagem-de-setups': typeof MontagemDeSetupsRoute
  '/personalizacao': typeof PersonalizacaoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/reforma-e-upgrade': typeof ReformaEUpgradeRoute
  '/suporte-tecnico': typeof SuporteTecnicoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/montagem-de-setups': typeof MontagemDeSetupsRoute
  '/personalizacao': typeof PersonalizacaoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/reforma-e-upgrade': typeof ReformaEUpgradeRoute
  '/suporte-tecnico': typeof SuporteTecnicoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/montagem-de-setups'
    | '/personalizacao'
    | '/politica-de-privacidade'
    | '/reforma-e-upgrade'
    | '/suporte-tecnico'
    | '/termos-de-uso'
    | '/portfolio/$slug'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/montagem-de-setups'
    | '/personalizacao'
    | '/politica-de-privacidade'
    | '/reforma-e-upgrade'
    | '/suporte-tecnico'
    | '/termos-de-uso'
    | '/portfolio/$slug'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/montagem-de-setups'
    | '/personalizacao'
    | '/politica-de-privacidade'
    | '/reforma-e-upgrade'
    | '/suporte-tecnico'
    | '/termos-de-uso'
    | '/portfolio/$slug'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MontagemDeSetupsRoute: typeof MontagemDeSetupsRoute
  PersonalizacaoRoute: typeof PersonalizacaoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ReformaEUpgradeRoute: typeof ReformaEUpgradeRoute
  SuporteTecnicoRoute: typeof SuporteTecnicoRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montagem-de-setups': {
      id: '/montagem-de-setups'
      path: '/montagem-de-setups'
      fullPath: '/montagem-de-setups'
      preLoaderRoute: typeof MontagemDeSetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizacao': {
      id: '/personalizacao'
      path: '/personalizacao'
      fullPath: '/personalizacao'
      preLoaderRoute: typeof PersonalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforma-e-upgrade': {
      id: '/reforma-e-upgrade'
      path: '/reforma-e-upgrade'
      fullPath: '/reforma-e-upgrade'
      preLoaderRoute: typeof ReformaEUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte-tecnico': {
      id: '/suporte-tecnico'
      path: '/suporte-tecnico'
      fullPath: '/suporte-tecnico'
      preLoaderRoute: typeof SuporteTecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MontagemDeSetupsRoute: MontagemDeSetupsRoute,
  PersonalizacaoRoute: PersonalizacaoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ReformaEUpgradeRoute: ReformaEUpgradeRoute,
  SuporteTecnicoRoute: SuporteTecnicoRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
